"""add timestamps to trader and notification

Revision ID: 742730301343
Revises: 4ab6cb1d0318
Create Date: 2025-05-30 00:18:56.647261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '742730301343'
down_revision: Union[str, None] = '4ab6cb1d0318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('traders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('traders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('traders', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traders', 'last_seen_at')
    op.drop_column('traders', 'updated_at')
    op.drop_column('traders', 'created_at')
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'created_at')
    # ### end Alembic commands ###
